### ISSUE TITLE
Audible popping in one of the examples

### ISSUE THREAD

**Issue by sushi-buffer** [defaultxr/cl-collider-tutorial#5]
Hi! Thanks for the great tutorial. 😃 
I'm currently playing around with noise based drums and when I played with some of the examples in the tutorial I found out that when using `perc` it results with audible digital pop after each time it's played. First I attempted to adjust release assuming the drop to 0 was too sharp, but I noticed that it simply happens every time, regardles of ADSR -settings on the `env-gen`.

I was wondering, if this is something that just happens on my machine, or is there something general that could affect the issue?

```lisp
(defsynth drum ((freq 3000))
  (let* ((env (env-gen.kr (perc 0.001 0.1) :act :free))
         (sig (lpf.ar (white-noise.ar) (* freq env))))
    (out.ar 0 (pan2.ar sig 0 0.2))))
```

**Comment by ntrocado** [comment]
Regardless of what may cause the problem, in my system changing `env-gen.kr` for the audio rate `env-gen.ar` makes the pop go away...

**Comment by defaultxr** [comment]
Weird, I don't hear any popping with `env-gen.kr`, nor with `env-gen.ar`. But I guess since the envelope is only affecting the filter cutoff and not the synth's volume, it's certainly possible that it could result in popping when the synth is freed. Thanks for pointing this out, I'll see if I can rewrite that example.

**Comment by ghost** [comment]
I can confirm that changing control rate to audio rate removes the popping :)

**Comment by defaultxr** [comment]
I was thinking about this more, and I think it's most likely not popping for me because I set SuperCollider's block size to be smaller, so `.kr` UGens are processed more often.

In any case, I changed chapter 4 in commit aa790b55b12ba413c1b94bf24f35b756bfc0232c. This should fix the issue, but let me know if you're still noticing this or any other issues.
